package com.sanggwonai.api.report.repository

import com.sanggwonai.api.report.service.ReviewTagAggregator
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * ReviewStorePoolRepository 실 Postgres 통합 테스트 (바운딩박스 SQL + haversine 정밀필터 검증).
 *
 * 평상시 빌드에선 비활성(REVIEW_POOL_IT=1 + Postgres 기동 시에만 실행).
 * 자체적으로 crawl_naver_* 테이블 생성·시드하므로 마이그레이션 불필요.
 */
@EnabledIfEnvironmentVariable(named = "REVIEW_POOL_IT", matches = "1")
class ReviewStorePoolRepositoryIT {

    private lateinit var jdbc: NamedParameterJdbcTemplate
    private lateinit var repo: ReviewStorePoolRepository

    private val baseLat = 37.5563
    private val baseLng = 126.9236

    @BeforeEach
    fun setup() {
        val ds = DriverManagerDataSource(
            System.getenv("TEST_DB_URL") ?: "jdbc:postgresql://localhost:5433/sanggwon_ai",
            System.getenv("TEST_DB_USERNAME") ?: "sanggwon",
            System.getenv("TEST_DB_PASSWORD") ?: "sanggwon"
        )
        jdbc = NamedParameterJdbcTemplate(ds)
        repo = ReviewStorePoolRepository(jdbc)

        val t = jdbc.jdbcTemplate
        t.execute(
            """
            create table if not exists crawl_naver_stores(
              id bigint generated by default as identity primary key,
              naver_place_id varchar(40) unique, name varchar(200), category varchar(200),
              address varchar(300), lat double precision, lng double precision,
              review_count int, voted_total int, voter_count int,
              scraped_at timestamptz, created_at timestamptz default now())
            """.trimIndent()
        )
        t.execute(
            """
            create table if not exists crawl_naver_store_tags(
              id bigint generated by default as identity primary key,
              store_id bigint references crawl_naver_stores(id) on delete cascade,
              tag varchar(200) not null, count int not null default 0, rank int,
              constraint uq_crawl_it unique(store_id, tag))
            """.trimIndent()
        )
        t.execute("truncate crawl_naver_store_tags, crawl_naver_stores restart identity cascade")

        // base(37.5563,126.9236), target=카페
        insert("A", "카페,디저트", 37.55640, 126.92368, 300, listOf("집중하기좋아요" to 200, "조용해요" to 50))   // ~14m 동종
        insert("B", "카페", 37.55625, 126.92350, 280, listOf("집중하기좋아요" to 150, "디저트가맛있어요" to 30)) // ~10m 동종
        insert("C", "카페,베이커리", 37.55648, 126.92372, 5, listOf("가성비좋아요" to 8, "양이많아요" to 2))      // ~22m 동종
        insert("D", "한식", 37.55635, 126.92355, 100, listOf("국밥맛집" to 50))                                  // 50m내지만 타업종 -> 제외
        insert("E", "카페", 37.55668, 126.92408, 90, listOf("뷰가좋아요" to 40))                                 // 박스 안·50m 밖(~60m) -> haversine 제외
    }

    private fun insert(pid: String, cat: String, lat: Double, lng: Double, voter: Int, tags: List<Pair<String, Int>>) {
        val voted = tags.sumOf { it.second }
        val id = jdbc.jdbcTemplate.queryForObject(
            "insert into crawl_naver_stores(naver_place_id,name,category,lat,lng,voted_total,voter_count) " +
                "values (?,?,?,?,?,?,?) returning id",
            Long::class.java, pid, pid, cat, lat, lng, voted, voter
        )!!
        tags.forEachIndexed { i, (tag, c) ->
            jdbc.jdbcTemplate.update(
                "insert into crawl_naver_store_tags(store_id,tag,count,rank) values (?,?,?,?)", id, tag, c, i + 1
            )
        }
    }

    @Test
    fun `50m 동종만 조회되고 타업종·박스모서리는 제외된다`() {
        val tokens = listOf("카페", "커피", "디저트", "베이커리")
        val stores = repo.findWithin(baseLat, baseLng, 50, tokens)

        val ids = stores.map { it.placeId }.toSet()
        assertEquals(setOf("A", "B", "C"), ids, "50m 내 동종(A,B,C)만 나와야 함. 타업종 D·50m밖 E 제외. 실제=$ids")

        // 태그 조인 정상
        val a = stores.first { it.placeId == "A" }
        assertTrue(a.tags.any { it.tag == "집중하기좋아요" && it.count == 200 }, "A 태그 조인 누락")

        // 집계기까지 end-to-end
        val insight = ReviewTagAggregator().build(stores, 50, "카페디저트")
        @Suppress("UNCHECKED_CAST")
        val demand = insight["demand_tags"] as List<Map<String, Any?>>
        assertEquals("집중하기좋아요", demand.first()["tag"], "붐비는 가게(A,B) 공통 태그가 수요 1위여야 함")
        @Suppress("UNCHECKED_CAST")
        val scope = insight["scope"] as Map<String, Any?>
        assertEquals(3, scope["store_count"])
    }
}
